import { resolvePrototypeLocale } from './locales';
import type { Locale } from './locales';

// Prototype drafts. No official/native-language or educational claim.
const copy = {
  'el-GR': {
    addition: 'Πόσα είναι όλα μαζί;',
    shape: 'Ποιο σχήμα ταιριάζει;',
    length: 'Πόσα βήματα έχει η γραμμή;',
    numeral: 'Ποια ομάδα ταιριάζει;',
    counting: 'Πόσες κουκκίδες βλέπεις;',
    comparison: 'Πού έχει πιο πολλά;',
    subtraction: 'Πόσες μένουν;',
    missing: 'Τι μπαίνει στο κενό;',
    left: 'Αριστερά',
    right: 'Δεξιά',
    part: 'Μέρος',
    all: 'Όλα μαζί',
    group: 'Ομάδα',
    dot: 'Κουκκίδα',
    removed: 'Έφυγε',
    empty: 'Καμία κουκκίδα',
    square: 'Τετράγωνο',
    rectangle: 'Ορθογώνιο',
    parallelogram: 'Πλάγιο σχήμα',
    fewer: 'Πιο πολλά δεξιά',
    same: 'Ίδιες',
    more: 'Πιο πολλά αριστερά',
    step: 'Ένα βήμα',
    start: 'Αρχή',
    firstStep: 'Πρώτο βήμα',
    nextStep: 'Επόμενο βήμα',
    lastStep: 'Τελευταίο βήμα',
    again: 'Από την αρχή',
    outline: 'Σχήμα με τέσσερις πλευρές',
    line: 'Γραμμή από ίσα βήματα',
    answers: 'Διάλεξε μια κάρτα',
    retry: 'Ξαναδοκίμασε',
    success: 'Ναι, το βρήκες!',
    wait: 'Μια στιγμή…',
    unavailable: 'Ζήτησε βοήθεια από έναν μεγάλο.',
    help: 'Δείξε μου',
    additionHelp: [
      'Βάλε τις δύο ομάδες μαζί.',
      'Κοίτα κάθε κουκκίδα.',
      'Άγγιξε τις κουκκίδες μία μία.',
    ],
    shapeHelp: [
      'Κοίτα τις γωνίες.',
      'Ακολούθησε τις πλευρές.',
      'Κοίτα και τις κάρτες.',
    ],
    lengthHelp: [
      'Κοίτα τα ίσα βήματα.',
      'Ακολούθησε τη γραμμή.',
      'Άγγιξε κάθε βήμα μία φορά.',
    ],
    numeralHelp: [
      'Κοίτα τον αριθμό και τις ομάδες.',
      'Βάλε τις κουκκίδες σε σειρά.',
      'Μέτρα κάθε ομάδα μία μία.',
    ],
    countingHelp: [
      'Βάλε τις κουκκίδες σε σειρά.',
      'Άγγιξε κάθε κουκκίδα.',
      'Κοίτα όσες δεν άγγιξες ακόμη.',
    ],
    comparisonHelp: [
      'Βάλε τις ομάδες δίπλα δίπλα.',
      'Ταίριαξε μία με μία.',
      'Κοίτα όσα μένουν μόνα.',
    ],
    subtractionHelp: [
      'Οι διαγραμμένες κουκκίδες έφυγαν.',
      'Κοίτα μόνο όσες μένουν.',
      'Άγγιξε όσες μένουν μία μία.',
    ],
    missingHelp: [
      'Κοίτα το κενό και όσα ξέρεις.',
      'Τα μέρη φτιάχνουν το σύνολο.',
      'Μέτρα όσα ξέρεις.',
    ],
  },
  'en-GB': {
    addition: 'How many altogether?',
    shape: 'Which shape matches?',
    length: 'How many steps along the line?',
    numeral: 'Which dots match?',
    counting: 'How many dots?',
    comparison: 'Where are there more dots?',
    subtraction: 'How many are left?',
    missing: 'What goes in the gap?',
    left: 'Left',
    right: 'Right',
    part: 'Part',
    all: 'Altogether',
    group: 'Group',
    dot: 'Dot',
    removed: 'Taken away',
    empty: 'No dots',
    square: 'Square',
    rectangle: 'Rectangle',
    parallelogram: 'Leaning shape',
    fewer: 'More on the right',
    same: 'Same',
    more: 'More on the left',
    step: 'One step',
    start: 'Start here',
    firstStep: 'First step',
    nextStep: 'Next step',
    lastStep: 'Last step',
    again: 'Start again',
    outline: 'Shape with four sides',
    line: 'Line made of equal steps',
    answers: 'Choose a card',
    retry: 'Try again',
    success: 'Yes, you found it!',
    wait: 'One moment…',
    unavailable: 'Ask a grown-up for help.',
    help: 'Show me',
    additionHelp: [
      'Bring both groups together.',
      'Look at every dot.',
      'Touch the dots one at a time.',
    ],
    shapeHelp: [
      'Look at the corners.',
      'Follow the sides.',
      'Look at the cards too.',
    ],
    lengthHelp: [
      'Look at the equal steps.',
      'Follow the line.',
      'Touch each step once.',
    ],
    numeralHelp: [
      'Look at the number and the groups.',
      'Line up the dots.',
      'Count each group one at a time.',
    ],
    countingHelp: [
      'Line up the dots.',
      'Touch each dot.',
      'Look for dots you have not touched.',
    ],
    comparisonHelp: [
      'Put the groups side by side.',
      'Match one with one.',
      'Look for any dots left over.',
    ],
    subtractionHelp: [
      'Crossed-out dots have gone.',
      'Look only at dots left.',
      'Touch those left one at a time.',
    ],
    missingHelp: [
      'Look at the gap and what you know.',
      'Parts make the whole.',
      'Use the dots you know.',
    ],
  },
  'de-DE': {
    addition: 'Wie viele sind es zusammen?',
    shape: 'Welche Form passt?',
    length: 'Wie viele Schritte hat die Linie?',
    numeral: 'Welche Punkte passen?',
    counting: 'Wie viele Punkte?',
    comparison: 'Wo sind mehr Punkte?',
    subtraction: 'Wie viele bleiben übrig?',
    missing: 'Was kommt in die Lücke?',
    left: 'Links',
    right: 'Rechts',
    part: 'Teil',
    all: 'Zusammen',
    group: 'Gruppe',
    dot: 'Punkt',
    removed: 'Weggenommen',
    empty: 'Keine Punkte',
    square: 'Quadrat',
    rectangle: 'Rechteck',
    parallelogram: 'Schräge Form',
    fewer: 'Rechts mehr',
    same: 'Gleich viele',
    more: 'Links mehr',
    step: 'Ein Schritt',
    start: 'Anfang',
    firstStep: 'Erster Schritt',
    nextStep: 'Nächster Schritt',
    lastStep: 'Letzter Schritt',
    again: 'Von vorn',
    outline: 'Form mit vier Seiten',
    line: 'Linie aus gleichen Schritten',
    answers: 'Wähle eine Karte',
    retry: 'Noch einmal',
    success: 'Ja, du hast es gefunden!',
    wait: 'Einen Moment…',
    unavailable: 'Bitte eine erwachsene Person um Hilfe.',
    help: 'Zeig es mir',
    additionHelp: [
      'Lege beide Gruppen zusammen.',
      'Schau jeden Punkt an.',
      'Berühre die Punkte einzeln.',
    ],
    shapeHelp: [
      'Schau die Ecken an.',
      'Folge den Seiten.',
      'Schau auch die Karten an.',
    ],
    lengthHelp: [
      'Schau die gleichen Schritte an.',
      'Folge der Linie.',
      'Berühre jeden Schritt einmal.',
    ],
    numeralHelp: [
      'Schau die Zahl und die Gruppen an.',
      'Ordne die Punkte in einer Reihe.',
      'Zähle jede Gruppe einzeln.',
    ],
    countingHelp: [
      'Ordne die Punkte in einer Reihe.',
      'Berühre jeden Punkt.',
      'Suche noch nicht berührte Punkte.',
    ],
    comparisonHelp: [
      'Lege die Gruppen nebeneinander.',
      'Ordne jedem Punkt einen zu.',
      'Suche übrige Punkte.',
    ],
    subtractionHelp: [
      'Durchgestrichene Punkte sind weg.',
      'Schau nur die übrigen Punkte an.',
      'Berühre die übrigen Punkte einzeln.',
    ],
    missingHelp: [
      'Schau die Lücke und Bekanntes an.',
      'Teile ergeben das Ganze.',
      'Nutze die bekannten Punkte.',
    ],
  },
} as const;

export function childCopy(locale: Locale) {
  return copy[resolvePrototypeLocale(locale).effectiveLocale];
}
